---

- apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- apt_repository:
    state: present
    repo: deb https://apt.dockerproject.org/repo ubuntu-{{ ubuntu_release }} main

- apt:
    name: "{{ item }}"
    state: "latest"
    install_recommends: False
    update_cache: yes
  with_items:
    - docker-engine
    - python-pip

- pip:
    name: "{{ item }}"
  with_items:
    - setuptools
    - docker-py
    - docker-compose

- user:
    append: yes
    groups: docker
    name: "{{ username }}"

- lineinfile:
    dest: /etc/default/locale
    line: 'LC_ALL="en_US.UTF-8"'
