---
- shell: gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
- shell: gpg --export 58118E89F3A912897C070ADBF76221572C52609D | sudo apt-key add -
- apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-wily main"
    state: present

- apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - docker-engine
  when: os_type == "debian"
  name: "apt-get install"

- shell: usermod -aG docker rguichard
  name: "add group docker"
