---

- hosts: localhost
  tasks:
    - name: add apt key
      apt_key:
        keyserver: hkp://ha.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D
    - name: add apt repo
      apt_repository:
        state: present
        repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    - name: install apt packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - git
        - python-pip
        - docker-engine
    - name: install pip packages
      pip:
        name: "{{ item }}"
      with_items:
        - ansible==2.3
