---
- apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - vim
  when: os_type == "debian"

- pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - vim
  when: os_type == "archlinux"

- copy: src=vimrc dest=~/.vimrc
- shell: vim +BundleInstall +qall
