---
- apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  sudo: yes
  with_items:
    - vim
  name: "INSTALL | git"

- copy: src=vimrc dest=~/.vimrc
  name: "import vimrc"

- shell: vim +BundleInstall +qall
  name: "vim bundle install"
