---
- apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - vim
  when: os_type == "debian"
  name: "apt-get install "

- copy: src=vimrc dest=~/.vimrc
  name: "import vimrc"

- shell: vim +BundleInstall +qall
  name: "vim bundle install"
