# ENV
#export PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:$HOME/.local/bin:/usr/sbin:/sbin:/usr/local/sbin"
ZSH=$HOME/.oh-my-zsh
POWERLINE=$HOME/.local/lib/python2.7/site-packages/powerline

# OH MY ZSH
ZSH_THEME="{{ zsh_theme }}"
COMPLETION_WAITING_DOTS="true"
# HIST_STAMPS="mm-dd-yyyy"
# CASE_SENSITIVE="true"
# DISABLE_AUTO_UPDATE="true"
# DISABLE_CORRECTION="true"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=({{ zsh_plugins }})

source $ZSH/oh-my-zsh.sh

# ALIASES
source $HOME/.aliases.local

# POWERLINE please comment this line if your don't have it installed
#. $POWERLINE/bindings/zsh/powerline.zsh

# COLORS
export TERM="xterm-256color"
eval `dircolors ~/.dircolors.256dark`

# ZSH PACKS
autoload -U zmv

export PATH="$PATH:$HOME/bin"
