---
- apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - git
  when: os_type == "debian"
  name: "apt-get install"

- template: src=gitconfig dest=~/.gitconfig
  name: "import gitconfig"
