- hosts: 127.0.0.1
  tasks:
    - apt:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - jq
        - curl
        - python
        - python-pip

    - name: create ~/.fonts
      file: path=~/.fonts state=directory

    - name: import PragmataPro font
      copy: src=files/PragmataPro-for-Powerline.otf dest=~/.fonts

    - name: refresh font
      shell: fc-cache -vf

    - file: path=~/.config/terminator state=directory
    - copy: src=files/terminator-config dest=~/.config/terminator/config

  roles:
    - git
    - vim
    - zsh
