- hosts: all
  tasks:
    - name: create ~/.fonts
      file: path=~/.fonts state=directory

    - name: import PragmataPro font
      copy: src=files/PragmataPro-for-Powerline.otf dest=~/.fonts
      when: machine_type == "desktop"

    - name: refresh font
      shell: fc-cache -vf
      when: machine_type == "desktop"

    - apt:
        name: "install {{ item }}"
        state: latest
      with_items:
        - vim
        - zsh
        - git
        - tmux
        - nmap
        - ncdu
        - jq
        - curl
        - tig
        - python
        - ptyhon-pip
      when: os_type == "debian"
      sudo: yes
  roles:
    - git
    - vim
    - zsh
    - docker

