- hosts: all
  tasks:
    - name: create ~/.fonts
      file: path=~/.fonts state=directory

    - name: import PragmataPro font
      copy: src=files/PragmataPro-for-Powerline.otf dest=~/.fonts
      when: machine_type == "desktop"

    - name: refresh font
      shell: fc-cache -vf
      when: machine_type == "desktop"

    - file: path=~/.config/terminator state=directory
    - copy: src=files/terminator-config dest=~/.config/terminator/config

    - apt:
        name: "install {{ item }}"
        state: latest
      sudo: yes
      with_items:
        - tmux
        - nmap
        - ncdu
        - jq
        - curl
        - tig
        - python
        - python-pip
      sudo: yes
  roles:
    - git
    - vim
    - zsh
    - docker

